- hosts: localhost
  connection: local
  gather_facts: False
  tasks:
    - name: Import VPC Variables
      include_vars: vars/vpc_setup

    - name: Create an EKS cluster
      aws_eks_cluster:
         name: my_cluster
         region: "{{region}}"
         role_arn: arn:aws:iam::622897596075:role/ansible-eks
         subnets:
            - subnet-c36603b8
            - subnet-34aefd78
         security_groups:
            - sg-0bf7f6c1adceb585f
      register: caller_facts
    - ec2:
         key_name: ansible-key
         instance_type: t2.micro
         image: ami-041d6256ed0f2061c
         count: 2
         region: "{{region}}"
         assign_public_ip: yes
         vpc_subnet_id: subnet-e4bf528f
