--- #playbook for vpc setup
- hosts: localhost
  connection: local
  gather_facts: False
  tasks:
     - name: Import VPC Variables
       include_vars: vars/vpc_setup 

     - name: Create vProfile VPC
       ec2_vpc_net:
          name: "{{vpc_name}}"
          cidr_block: "{{vpcCidr}}"
          region: "{{region}}"
          dns_support: yes
          dns_hostnames: yes
          tenancy: default
          state: "{{state}}"
       register: vpcout 
     - debug: 
         var: vpcout
     - name: create create Public Subnet in Zone1
       ec2_vpc_subnet:
         vpc_id: "{{vpcout.vpc.id}}"
         region: "{{region}}"
         az: "{{zone1}}"
         state: "{{state}}"
         cidr: "{{ PubSubCidr }}"
         map_public: yes
         resource_tags:
            name: vprofile_public_subnet
      register: pubsub_out
      - name: create create Private Subnet in Zone
        ec2_vpc_subnet:
         vpc_id: "{{vpcout.vpc.id}}"
         region: "{{region}}"
         az: "{{zone1}}"
         state: "{{state}}"
         cidr: "{{ PrivSubCidr }}"
         resource_tags:
            name: vprofile_private_subnet
      register: privatesub_out

